apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring-dev

resources:
  - ../base

patches:
  - target:
      kind: ConfigMap
      name: ktcloud-lb-dashboards
    patch: |-
      - op: add
        path: /metadata/labels/app.kubernetes.io~1instance
        value: prometheus-dev

