apiVersion: v1
kind: Service
metadata:
  name: lb-exporter-account2 # 다른 이름으로 지정
  namespace: monitoring
  labels:
    app: lb-exporter-account2
spec:
  selector:
    app: lb-exporter-account2
  ports:
    - protocol: TCP
      port: 9105
      targetPort: metrics
      name: metrics
