apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-lb-exporter
  namespace: monitoring-dev
  labels:
    app: lb-exporter
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-exporter
      environment: dev
  template:
    metadata:
      labels:
        app: lb-exporter
        environment: dev
    spec:
      containers:
        - name: lb-exporter
          image: registry.cloud.kt.com/nqtv7l5h/lb-exporter:develop-latest
          ports:
            - containerPort: 9105
              name: metrics
          env:
            - name: CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ID
            - name: CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_PASSWORD
            - name: CLOUD_ZONE
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ZONE
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9105
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9105
            initialDelaySeconds: 5
            periodSeconds: 5