apiVersion: v1
kind: Service
metadata:
  name: dev-lb-exporter
  namespace: monitoring-dev
  labels:
    app: lb-exporter
    environment: dev
spec:
  selector:
    app: lb-exporter
    environment: dev
  ports:
  - port: 9105
    targetPort: 9105
    name: metrics
  type: ClusterIP