apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-exporter
  namespace: monitoring
  labels:
    app: lb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-exporter
  template:
    metadata:
      labels:
        app: lb-exporter
    spec:
      containers:
        - name: lb-exporter
          image: registry.cloud.kt.com/nqtv7l5h/lb-exporter:v1.0.1 # 위에서 푸시한 Docker 이미지
          ports:
            - containerPort: 9105 # lb-exporter.py에 설정된 포트
              name: metrics
          env:
            # Secret에서 환경 변수 로드
            - name: CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ID
            - name: CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_PASSWORD
            - name: CLOUD_ZONE
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ZONE
          # Liveness/Readiness Probe 추가 (선택 사항이지만 권장)
          # readinessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: 9105
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /metrics
          #     port: 9105
          #   initialDelaySeconds: 30
          #   periodSeconds: 30
      imagePullSecrets:
        - name: ktcloud-registry-secret # kubectl create secret 명령어로 생성했던 secret의 이름
