apiVersion: apps/v1
kind: Deployment
metadata:
  name: staging-lb-exporter
  namespace: monitoring-staging
  labels:
    app: lb-exporter
    version: v1.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-exporter
  template:
    metadata:
      labels:
        app: lb-exporter
    spec:
      containers:
        - name: lb-exporter
          image: registry.cloud.kt.com/nqtv7l5h/lb-exporter:v1.0.1
          ports:
            - containerPort: 9105
              name: metrics
          env:
            - name: CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ID
            - name: CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_PASSWORD
            - name: CLOUD_ZONE
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ZONE
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: staging-lb-exporter
  namespace: monitoring-staging
  labels:
    app: lb-exporter
spec:
  selector:
    app: lb-exporter
  ports:
  - port: 9105
    targetPort: 9105
    name: metrics