apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-lb-exporter
  namespace: monitoring
  labels:
    app: lb-exporter
    environment: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lb-exporter
      environment: prod
  template:
    metadata:
      labels:
        app: lb-exporter
        environment: prod
    spec:
      containers:
        - name: lb-exporter
          image: registry.cloud.kt.com/nqtv7l5h/lb-exporter:v1.0.1
          ports:
            - containerPort: 9105
              name: metrics
          env:
            - name: CLOUD_ID
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ID
            - name: CLOUD_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_PASSWORD
            - name: CLOUD_ZONE
              valueFrom:
                secretKeyRef:
                  name: ktcloud-lb-exporter-secrets
                  key: CLOUD_ZONE
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /metrics
              port: 9105
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 9105
            initialDelaySeconds: 5
            periodSeconds: 5