apiVersion: v1
kind: Service
metadata:
  name: prod-lb-exporter
  namespace: monitoring
  labels:
    app: lb-exporter
    environment: prod
spec:
  selector:
    app: lb-exporter
    environment: prod
  ports:
  - port: 9105
    targetPort: 9105
    name: metrics
  type: ClusterIP