apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: staging-lb-exporter
  namespace: monitoring-staging
  labels:
    app: lb-exporter
    environment: staging
    release: prometheus-staging
spec:
  selector:
    matchLabels:
      app: lb-exporter
      environment: staging
  endpoints:
  - port: metrics
    interval: 60s
    path: /metrics
    honorLabels: true
    scrapeTimeout: 20s
  namespaceSelector:
    matchNames:
    - monitoring-staging