apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lb-exporter-prod-gitops
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Upwardh/gitops-k2p.git
    targetRevision: main
    path: gitops/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-prod
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true