apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lb-exporter-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ktcloud-lb-monitoring
  source:
    repoURL: https://github.com/Upwardh/gitops-k2p.git
    targetRevision: main
    path: environments/staging/lb-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m